// Older protoc compilers don't understand edition yet.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: a2a.proto

package a2apb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	A2AService_SendMessage_FullMethodName                      = "/lf.a2a.v1.A2AService/SendMessage"
	A2AService_SendStreamingMessage_FullMethodName             = "/lf.a2a.v1.A2AService/SendStreamingMessage"
	A2AService_GetTask_FullMethodName                          = "/lf.a2a.v1.A2AService/GetTask"
	A2AService_ListTasks_FullMethodName                        = "/lf.a2a.v1.A2AService/ListTasks"
	A2AService_CancelTask_FullMethodName                       = "/lf.a2a.v1.A2AService/CancelTask"
	A2AService_SubscribeToTask_FullMethodName                  = "/lf.a2a.v1.A2AService/SubscribeToTask"
	A2AService_CreateTaskPushNotificationConfig_FullMethodName = "/lf.a2a.v1.A2AService/CreateTaskPushNotificationConfig"
	A2AService_GetTaskPushNotificationConfig_FullMethodName    = "/lf.a2a.v1.A2AService/GetTaskPushNotificationConfig"
	A2AService_ListTaskPushNotificationConfigs_FullMethodName  = "/lf.a2a.v1.A2AService/ListTaskPushNotificationConfigs"
	A2AService_GetExtendedAgentCard_FullMethodName             = "/lf.a2a.v1.A2AService/GetExtendedAgentCard"
	A2AService_DeleteTaskPushNotificationConfig_FullMethodName = "/lf.a2a.v1.A2AService/DeleteTaskPushNotificationConfig"
)

// A2AServiceClient is the client API for A2AService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides operations for interacting with agents using the A2A protocol.
type A2AServiceClient interface {
	// Sends a message to an agent.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Sends a streaming message to an agent, allowing for real-time interaction and status updates.
	// Streaming version of `SendMessage`
	SendStreamingMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// Gets the latest state of a task.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Lists tasks that match the specified filter.
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Cancels a task in progress.
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Subscribes to task updates for tasks not in a terminal state.
	// Returns `UnsupportedOperationError` if the task is already in a terminal state (completed, failed, canceled, rejected).
	SubscribeToTask(ctx context.Context, in *SubscribeToTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// (-- api-linter: client-libraries::4232::required-fields=disabled
	//
	//	api-linter: core::0133::method-signature=disabled
	//	api-linter: core::0133::request-message-name=disabled
	//	aip.dev/not-precedent: method_signature preserved for backwards compatibility --)
	//
	// Creates a push notification config for a task.
	CreateTaskPushNotificationConfig(ctx context.Context, in *TaskPushNotificationConfig, opts ...grpc.CallOption) (*TaskPushNotificationConfig, error)
	// Gets a push notification config for a task.
	GetTaskPushNotificationConfig(ctx context.Context, in *GetTaskPushNotificationConfigRequest, opts ...grpc.CallOption) (*TaskPushNotificationConfig, error)
	// Get a list of push notifications configured for a task.
	ListTaskPushNotificationConfigs(ctx context.Context, in *ListTaskPushNotificationConfigsRequest, opts ...grpc.CallOption) (*ListTaskPushNotificationConfigsResponse, error)
	// Gets the extended agent card for the authenticated agent.
	GetExtendedAgentCard(ctx context.Context, in *GetExtendedAgentCardRequest, opts ...grpc.CallOption) (*AgentCard, error)
	// Deletes a push notification config for a task.
	DeleteTaskPushNotificationConfig(ctx context.Context, in *DeleteTaskPushNotificationConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type a2AServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewA2AServiceClient(cc grpc.ClientConnInterface) A2AServiceClient {
	return &a2AServiceClient{cc}
}

func (c *a2AServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, A2AService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) SendStreamingMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &A2AService_ServiceDesc.Streams[0], A2AService_SendStreamingMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SendStreamingMessageClient = grpc.ServerStreamingClient[StreamResponse]

func (c *a2AServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, A2AService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, A2AService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, A2AService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) SubscribeToTask(ctx context.Context, in *SubscribeToTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &A2AService_ServiceDesc.Streams[1], A2AService_SubscribeToTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToTaskRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SubscribeToTaskClient = grpc.ServerStreamingClient[StreamResponse]

func (c *a2AServiceClient) CreateTaskPushNotificationConfig(ctx context.Context, in *TaskPushNotificationConfig, opts ...grpc.CallOption) (*TaskPushNotificationConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPushNotificationConfig)
	err := c.cc.Invoke(ctx, A2AService_CreateTaskPushNotificationConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) GetTaskPushNotificationConfig(ctx context.Context, in *GetTaskPushNotificationConfigRequest, opts ...grpc.CallOption) (*TaskPushNotificationConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPushNotificationConfig)
	err := c.cc.Invoke(ctx, A2AService_GetTaskPushNotificationConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) ListTaskPushNotificationConfigs(ctx context.Context, in *ListTaskPushNotificationConfigsRequest, opts ...grpc.CallOption) (*ListTaskPushNotificationConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskPushNotificationConfigsResponse)
	err := c.cc.Invoke(ctx, A2AService_ListTaskPushNotificationConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) GetExtendedAgentCard(ctx context.Context, in *GetExtendedAgentCardRequest, opts ...grpc.CallOption) (*AgentCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentCard)
	err := c.cc.Invoke(ctx, A2AService_GetExtendedAgentCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AServiceClient) DeleteTaskPushNotificationConfig(ctx context.Context, in *DeleteTaskPushNotificationConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, A2AService_DeleteTaskPushNotificationConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// A2AServiceServer is the server API for A2AService service.
// All implementations must embed UnimplementedA2AServiceServer
// for forward compatibility.
//
// Provides operations for interacting with agents using the A2A protocol.
type A2AServiceServer interface {
	// Sends a message to an agent.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Sends a streaming message to an agent, allowing for real-time interaction and status updates.
	// Streaming version of `SendMessage`
	SendStreamingMessage(*SendMessageRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// Gets the latest state of a task.
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	// Lists tasks that match the specified filter.
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Cancels a task in progress.
	CancelTask(context.Context, *CancelTaskRequest) (*Task, error)
	// Subscribes to task updates for tasks not in a terminal state.
	// Returns `UnsupportedOperationError` if the task is already in a terminal state (completed, failed, canceled, rejected).
	SubscribeToTask(*SubscribeToTaskRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// (-- api-linter: client-libraries::4232::required-fields=disabled
	//
	//	api-linter: core::0133::method-signature=disabled
	//	api-linter: core::0133::request-message-name=disabled
	//	aip.dev/not-precedent: method_signature preserved for backwards compatibility --)
	//
	// Creates a push notification config for a task.
	CreateTaskPushNotificationConfig(context.Context, *TaskPushNotificationConfig) (*TaskPushNotificationConfig, error)
	// Gets a push notification config for a task.
	GetTaskPushNotificationConfig(context.Context, *GetTaskPushNotificationConfigRequest) (*TaskPushNotificationConfig, error)
	// Get a list of push notifications configured for a task.
	ListTaskPushNotificationConfigs(context.Context, *ListTaskPushNotificationConfigsRequest) (*ListTaskPushNotificationConfigsResponse, error)
	// Gets the extended agent card for the authenticated agent.
	GetExtendedAgentCard(context.Context, *GetExtendedAgentCardRequest) (*AgentCard, error)
	// Deletes a push notification config for a task.
	DeleteTaskPushNotificationConfig(context.Context, *DeleteTaskPushNotificationConfigRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedA2AServiceServer()
}

// UnimplementedA2AServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedA2AServiceServer struct{}

func (UnimplementedA2AServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedA2AServiceServer) SendStreamingMessage(*SendMessageRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SendStreamingMessage not implemented")
}
func (UnimplementedA2AServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedA2AServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedA2AServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedA2AServiceServer) SubscribeToTask(*SubscribeToTaskRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToTask not implemented")
}
func (UnimplementedA2AServiceServer) CreateTaskPushNotificationConfig(context.Context, *TaskPushNotificationConfig) (*TaskPushNotificationConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTaskPushNotificationConfig not implemented")
}
func (UnimplementedA2AServiceServer) GetTaskPushNotificationConfig(context.Context, *GetTaskPushNotificationConfigRequest) (*TaskPushNotificationConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskPushNotificationConfig not implemented")
}
func (UnimplementedA2AServiceServer) ListTaskPushNotificationConfigs(context.Context, *ListTaskPushNotificationConfigsRequest) (*ListTaskPushNotificationConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskPushNotificationConfigs not implemented")
}
func (UnimplementedA2AServiceServer) GetExtendedAgentCard(context.Context, *GetExtendedAgentCardRequest) (*AgentCard, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExtendedAgentCard not implemented")
}
func (UnimplementedA2AServiceServer) DeleteTaskPushNotificationConfig(context.Context, *DeleteTaskPushNotificationConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaskPushNotificationConfig not implemented")
}
func (UnimplementedA2AServiceServer) mustEmbedUnimplementedA2AServiceServer() {}
func (UnimplementedA2AServiceServer) testEmbeddedByValue()                    {}

// UnsafeA2AServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to A2AServiceServer will
// result in compilation errors.
type UnsafeA2AServiceServer interface {
	mustEmbedUnimplementedA2AServiceServer()
}

func RegisterA2AServiceServer(s grpc.ServiceRegistrar, srv A2AServiceServer) {
	// If the following call panics, it indicates UnimplementedA2AServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&A2AService_ServiceDesc, srv)
}

func _A2AService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_SendStreamingMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(A2AServiceServer).SendStreamingMessage(m, &grpc.GenericServerStream[SendMessageRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SendStreamingMessageServer = grpc.ServerStreamingServer[StreamResponse]

func _A2AService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_SubscribeToTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(A2AServiceServer).SubscribeToTask(m, &grpc.GenericServerStream[SubscribeToTaskRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AService_SubscribeToTaskServer = grpc.ServerStreamingServer[StreamResponse]

func _A2AService_CreateTaskPushNotificationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskPushNotificationConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).CreateTaskPushNotificationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_CreateTaskPushNotificationConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).CreateTaskPushNotificationConfig(ctx, req.(*TaskPushNotificationConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_GetTaskPushNotificationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskPushNotificationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).GetTaskPushNotificationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_GetTaskPushNotificationConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).GetTaskPushNotificationConfig(ctx, req.(*GetTaskPushNotificationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_ListTaskPushNotificationConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskPushNotificationConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).ListTaskPushNotificationConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_ListTaskPushNotificationConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).ListTaskPushNotificationConfigs(ctx, req.(*ListTaskPushNotificationConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_GetExtendedAgentCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtendedAgentCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).GetExtendedAgentCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_GetExtendedAgentCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).GetExtendedAgentCard(ctx, req.(*GetExtendedAgentCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AService_DeleteTaskPushNotificationConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskPushNotificationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AServiceServer).DeleteTaskPushNotificationConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AService_DeleteTaskPushNotificationConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AServiceServer).DeleteTaskPushNotificationConfig(ctx, req.(*DeleteTaskPushNotificationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// A2AService_ServiceDesc is the grpc.ServiceDesc for A2AService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A2AService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lf.a2a.v1.A2AService",
	HandlerType: (*A2AServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _A2AService_SendMessage_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _A2AService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _A2AService_ListTasks_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _A2AService_CancelTask_Handler,
		},
		{
			MethodName: "CreateTaskPushNotificationConfig",
			Handler:    _A2AService_CreateTaskPushNotificationConfig_Handler,
		},
		{
			MethodName: "GetTaskPushNotificationConfig",
			Handler:    _A2AService_GetTaskPushNotificationConfig_Handler,
		},
		{
			MethodName: "ListTaskPushNotificationConfigs",
			Handler:    _A2AService_ListTaskPushNotificationConfigs_Handler,
		},
		{
			MethodName: "GetExtendedAgentCard",
			Handler:    _A2AService_GetExtendedAgentCard_Handler,
		},
		{
			MethodName: "DeleteTaskPushNotificationConfig",
			Handler:    _A2AService_DeleteTaskPushNotificationConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStreamingMessage",
			Handler:       _A2AService_SendStreamingMessage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToTask",
			Handler:       _A2AService_SubscribeToTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "a2a.proto",
}
